language: java
jdk:
- oraclejdk8
os: linux
dist: trusty
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn clean compiler:compile compiler:testCompile validate surefire:test package
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  overwrite: true
  api_key:
    secure: VbUEN+Dj51gjXXekwTmNegffvCUqJ1we9qbFVjoJtZk0y9asyuu3YqAbKpOASIC4wlLcjWAH1glNnMNCI1d3i3j8HXfzQaY1/k0RUL2ziOcO15YE5DkXz7wBKMih8mYg1ZcF9lRmEcdKYSi9OlrnSpuFXEUP4OQwmZM4DoBuOSk8gD0ja7WRwKmXiTP0MZHUrK3AYtWvMogB8Gt9GaLtKlIZpPi6m5BztKJZnBA997hxznFdd4V5tywntbKDd9BuBc8pJV0p9ZGx0rS7wxata6HDht0CG/pgZruk9bdsatYgWQ+4f2aG5duvv+KQReTM8vXn2aLAMBbwPZyKV/EG5IvW2tzjfVK49BRkfnMLfyEePoMTJQ6DuF21SBfM50iV3CsUDszwqlT9TfA7FSZXkR8rvcCTyHb7aBdsYADHzL7XyPophCuExqT1AgjJ0o+6TgybKdpfhdAf9JBcRRvnLj95aO7eg/ixupjkuK5objdNCO3yykwPHXjhFjBt6eGpyl10cYy2BDhNuXBRXjL+rs8jPUTGQBw4otlrshim7p79i7/yaEVW5b0KtQ+XAye2aQ1YlGBJ027Y02QYH0lUFUwNAB3oW8QiJfkDpceIr94+u5mQOG5J9S2Kufl4/tgsfg8RNgGgCMZASkC4qXZfsC1cGASFup8pT1fsypI9t3M=
  file:
  - "./target/*.jar"
  - "./target/*.zip"
  on:
    repo: AdminOfThis/Frequent
    tags: true
