language: java
jdk:
- oraclejdk8
os:
- linux
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  - provider: releases
    skip_cleanup: true
    prerelease: true
    overwrite: true
    api_key:
      secure: SpYg6TM1B2GuiV4Fitq/GjpMbEMRSk/1UWmc+0GTGH9XAsrgx6K5PhAD9bmUxDX0sBmi3PkmkpFKRZ/5PzcTvJvTad3HfC8qg84l+KTJ/1CIJQRy8Ov5a7Pej9pq3wowMdyYFMpRfe43uZkV/6hmhrUohuW1vZNsYp8rd3D1n+4LtpDNlIZfnnrvw4XEKxoQ1AT6e4+FOVL55qEBoVQxaZOTin/SBrAULMrv9p4w21Ijj1Rj/2UzaW96LCTKk6+nmMY3rapCRAXB0I2jkjOLR0UjfDrfs9seCYImk943jOvut9KIed/KY5cBI6zwUj498VL8DcLfr6iUqQZg+ca6sCEGRMd0Gu5OSb7DuzmkLT9yy3wq7lqQGmv18pSvX+FRt2vcUqmacmsBzOiuerk8rgDQrhST/+tknetHBYHgDM/7Q/7auWEq59hueH4T2x0eaZfEWdl4ik8j1UxIfQFr+WhlqwmxAsTd5Hft6SuZkjHVq3fYLnunAhbZ4MSPA81wAxCfJXRZDTCd5GdF1rHxPCUfy6iThm02r8xACWZWPnsFgZbl7n/fUHRsc/j0YewmWoFqjYXzhSEs6Wk9iDDS/6JwbeUeBi0wO2Twz00Fk1r7b1QZ9vxVHom0LKAKOUMnzyDNR+EAhd/kMMFkhjDLOu99uj2I2gJfjuT+sKdhcTY=
    file_glob: true
    file: "./*.jar"
    on:
      repo: AdminOfThis/Frequent
      tags: true
  - provider: bintray
    skip_cleanup: true
    file: "./*.jar"
    user: "AdminOfThis"
    key:
      secure: M/FzpgsSdlUmlTT884SEujk/ZLJF6sho705MQB+8UnXUW1WZ8kOydGOVoXQT1LqJ4OyMTmL7WMSktKS0hpc/GWZ0BWpEMGZJ/jyREVvTEGZyd6FjFdOIedGVR3/tIWOm65X+VnQIFIeGNPPskRA6wUOzsmAPdfBStwT0H5yaLUDHoMohxVbFdCrbPB0TjthxiH9PdDkUwjbJBSLwIs2x5uh+gXcFRcy8D+c5plnqUeif08eIhYTBxPlCdcWLFb/u+XnwQhtM/zbBsG/eMd8MCiQAJYXsSMlg9Oxp83FZDQfbJNI7KDcTQvP8Oe4fldvlR6vvVjYlyq3K1QrS5IAhp71DowDsgapfprhhqJnTHpvYBp0VSBsVo98FAX93Q7117lL4LVnpNCI0Wt6eBor4LxZax/nk6xPYz1QgTgnWouKrSy/iIvmreOEJCWFBG84LCx+2Lcw7d0DXUnVP6t7LW2Sj+RQ/W0MpoBYJv5kzDddjTuAn74R+vQP6T96/V2nZTfyDUXb4iocO79GTlhQIWW9dDubQIdxDHoXO63uYlbq3EtWFrcENUStGyXDuWWhZrKrhaEi81uSzEOmCfC0uA340pD5wR+O7a4NV1FeNVbeaaNl32uTLZHmExbvh4Nc8uoZ5QZah3ovD/N/f2Xr9pMldwRqdLRDRZ1x8z1r0PXI=