language: java
jdk:
- oraclejdk8
os: linux
dist: trusty
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn clean compiler:compile compiler:testCompile validate surefire:test package
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  overwrite: true
  api_key:
    secure: RkIOXXkl3+78q0gF8eZrWT60dKFRQFaJUXmsid7UZn8aNmLdjB14gVklFFzQrxsoEKpQwvSLQ29Pa6zfyukapi6BEi4F7yf3PYgAI6t2gK0fZNWWz9J+iIoPi4qzWo8WQQeSk2HevLs6xC58LAVBgcN9dnF0jfk1Ghh+crBJawgH+vqHZNUevMjkSd2qEAIxlU41RFmQh41P/iVm10PlKY+KRraq9rQSNVNLwOf3qYSjx+cD0nlosFwxv/gEVjLKJbwZyQRnVCX7vgrQopsByMGRsCRifwYxBtBjqAUknHwVxOnpS61WyIkgtR5u13WNHN+iJuEM7fZddKvA0OhiMyhGOA2rQSrgTNyfjuY29ZZ+8QI/ewggAi7OaOorE8RNi+0rADdvfd4QuHnuZ6+Tp0k5S7mRw96zlgPFdpoxuhBbmnInXP6AbDyCd/eKN2nfartBaS0WfG11oWD8BjQyWoH+KZooJc8G7U2j4/KzQMwcMZDq4BL2/zNggecauVqWvdF9im4Xz00MB5giwMYTBq88JC5JW3HfQGFMghGemGEv08Y8V0nnf6gVBgTK+K9WQFfLcx8V2TOg19rdGq/wS5CJhM5pVmH0+Qo1AyaDToP8PpxXzql+uSBJvL6H7ohcqor9/IhknRx2ttVs7c31oKmfJkil1CYolh+WxPvM2hI=
  file: 
    - "./target/*.jar"
    - "./target/*.zip"
  on:
    repo: AdminOfThis/Frequent
    tags: true
