language: java
jdk:
- oraclejdk8
os: linux
dist: trusty
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn clean compiler:compile compiler:testCompile validate surefire:test package
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  overwrite: true
  user: "AdminOfThis"
  api_key:
    secure: "j1v2FZ7puXgHleswKNsUmWebyq2ZVmeq9Pzo/Tf9DAcI/NLvyiKM7vXM/GOannaYDtC1fsrg54kKYp7FrgmSBJ/qXNn0VOEZNJnZssFTjTzTDE2m3fXOS2Q4XF+M1WN1tVfXTa1yIjDFMN9t+DFrFAXcPnumdk+loA5IFq7t9jjU4j10pW5N04FXrYcRwGPyzatIIhULmFd7eFOi+vbXws29G7vp1HRB80Cr9GwaRe8u72eZz4b9M9PuvPh/Yqs0W/n3iRnShFu2TnJ29lMO6eM5u/qYHA6maFYLtuZl6/UnewZGMMpmTFU380cLEPF5h/J78U1tmUT/N13NzdK3vrdT15AgvpKqSFPjshAEoBwnbDDHwxAVmP19Uz7hDfNdafkJjeIagMyYTSamjiwAymfIXWzYBYk4AXVi5ymng7AclqLI5+4pOYNldiFRQz6LeLgNtSu74W1OhGUptW3XTCqzZ9I9LUEG49mE32JdyDFeIo3sTHP3GBUewOmYalNaWcmTgN0iCgbQavbQPZvPLA26CLYE3NAzfwwJ8n6lZYqoEyH4n3pSOE84E3DhrRmaYqXj8CthK8L6V4PDSmfqY2pBk2gG0kZaq9iWUYtEgqoPa47TKm79L+gip4MSWWCfcRUd3F+QrgS3QJCp4JDtXXKum/xtLNtl0AD+8oqF5/4="
  file:
  - "./target/*.jar"
  - "./target/*.zip"
  on:
    repo: AdminOfThis/Frequent
    tags: true