language: java
install: ant
script: ant -file build.xml
os: windows
addons:
    apt:
      update: true
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key: 0f4a653caae6826e60fc60e31c8da7fbcf53bcac
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true