language: java
jdk:
- oraclejdk8
os: linux
dist: trusty
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn clean compiler:compile compiler:testCompile validate surefire:test package
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  overwrite: true
  api_key:
    secure: bU4Wnwolzul9Yl28y2kGk7RmBmmr8iz9ysUpvBKSQFUlgMxAk/m9tfAtO03M89tdn25vXVFDaS0n99F26n5BXAEgiw4EbW5KAA9UwdGLAHBIFaENtZa8hl4G4KJigczwavy34eje96ykNveZ61MfiL+O5CtlpScg/PLF9FiGwMxlbIVIIAqyoqZo4jQP2XYZNufSnvbnpIKZtiQDw7/RvqysgNYCdYfJVWp3IJz4j5jA9DOxMc0Ut8r+KBXGWT55TOsLh+28JKIIU9tbr3WWdohClKP5r9cZYfy9V0dHmfBbW3BsTEtCbCkHj+wYpiDxet0ibDnWIeWe0O8RJ/rRCUVJjG1tGSJc1ZtQ1gMke0rLKaTIIslGp9SOXKhqy7Vsg+ioedICrPDu7b+thlugQdeM5wLIRmXsKJKGF8rUKp4cWF5JhfOLLJvZWTkihNRXDtT9oGBSuITYmR+GQUxXcj8bAWUPQ7mqaPUjPMCGo99rf6nD8hxLFAMZKJJRzmj7QqU3BWezOfLwCjXegrxu2AIiTN7ZRVb7xpMT0++5HuOUXVtUQ1av2ZGdlv4kRAT/t/efgSKqeeUHIwwrxy0bXNR8egUZQJms++Tek4TN7lP34swtvc9OEdapD9KISVXA9iNhJ47+JIpinD8SzReMyrl3smT8YJca9erd6HCmR/s=
  file: 
    - "./target/*.jar"
    - "./target/*.zip"
  on:
    repo: AdminOfThis/Frequent
    tags: true
