language: java
jdk:
- oraclejdk8
os: linux
dist: trusty
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn clean compiler:compile compiler:testCompile validate surefire:test package
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  overwrite: true
  user: "AdminOfThis"
  api_key:
    secure: "dSXQDiDsgi92s/ZGo2QXhKKiNIT28vGJNJSx8Uo66D66AqkmjxKeAtJQDQYJUsW29zsN60eVdcQ8PPtdMsBZxe+gtJctmfu8+DlhSMEFLcqnD+Fam+tZ40OATQyHplrulSDvlf3bim72eZEkJjTdGU2Y2ZjQQzzLE3+HrvjmIGdn/bLu17E8zPmuwZzkeh9TVby1W0rhxRo0/iFmOwwzX3+oNLsvtXDps219k4nZetxUt7qUh4G+bZNU3wa2ojg/dCBwUp1OcmQWHF7CoQCRp5UI5IWSAPViE5WPtJYZl2K3HWdtYymRfDRSnfsMt8OjrwpZaYg7Pzre3+pwaDR38OC29QIBhsy0qdgZ91JGS4ocv33u7VvNQfOlmmDLHFAeHXMf4hAQ6AQV0dHIxyaBxEkpk441nT9IUOLWqFyn7SJUJFs9Q7VHlU1XgfJ5XsWXrvl+WX1m3u17YYtyEOTcCo0S18t9LLJ/JSWLbC0ir/gTqm7BfOwN7ZJN4LbT/ZAao3OTekOZMRVz8OmgRY7lBZrF8+wRClcNhthAnxthoXL/6kZnF1pFuHTTamc8EKgLcHsDUBlnx6qtUjSnWa4/lswysfjQMch1S8lhjis+BfWPWYuYt1ILrL+WzjypH/flSbWaw0gKjJIktlXgmDD56HAwwYBmpqqIMMoVOJMYtJQ="
  file:
  - "./target/*.jar"
  - "./target/*.zip"
  on:
    repo: AdminOfThis/Frequent
    tags: true