name: Build

on: [push, pull_request]

jobs:
  build:
    env:
      maven: mvn clean compiler:compile compiler:testCompile validate surefire:test package --file pom.xml
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
        # if os is ubuntu, run on xvfb
        - os: ubuntu-latest
          maven: xvfb-run mvn clean compiler:compile compiler:testCompile validate surefire:test package --file pom.xml
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.1'
        architecture: x64
    - name: Java Version
      run: java -version
    - name: Run Maven (Linux)
      if: matrix.os == 'ubuntu_latest'
      run: xvfb-run ${maven}
    - name: Run Maven
      if: matrix.os != "ubuntu_latest'
      run: ${maven}
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Frequent
        path: ./target/Frequent.zip
  
