name: Build

on: [push, pull_request]

jobs:
  build:
    env:
     _JAVA_OPTIONS: "-Dtestfx.headless=true -Djava.library.path=. -Djni.library.path=."
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.2
      with:
        submodules: recursive
    - name: Set up JDK 13
      uses: actions/setup-java@v1.4.0
      with:
        java-version: '13.0.1'
    - name: Run Maven (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: xvfb-run mvn clean compiler:compile compiler:testCompile initialize pre-integration-test validate surefire:test verify package --file pom.xml
    - name: Run Maven
      if: matrix.os != 'ubuntu-latest'
      run: mvn clean compiler:compile compiler:testCompile initialize pre-integration-test validate surefire:test verify package --file pom.xml
    - name: Upload Coverage Files
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v1.0.12
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./target/site/jacoco/jacoco.xml #optional
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Frequent
        path: ./target/Frequent.zip
