name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0
      with:
        submodules: recursive
    - name: Set up JDK 13
      uses: actions/setup-java@v2
      with:
        java-version: 13
        distribution: adopt
        java-package: jdk
        architecture: x64
    - name: Run Maven
      run: mvn clean compiler:compile compiler:testCompile initialize pre-integration-test validate surefire:test verify package --file pom.xml
    - name: Upload Coverage Files
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./target/site/jacoco/jacoco.xml #optional
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Frequent
        path: ./target/Frequent.zip
